### ISSUE TITLE
Do you plan to share a "road map" for further enhancements?

### ISSUE THREAD

**Issue by mi-hol** [dunderrrrrr/openmediavault-fastapi-docker#1]
Great approach!
From looking at the code it seems that further enhancements are planned (i.e. comments like  "Real Memory Usage from openmediavault")

Do you plan to share a "road map" for further enhancements?

**Comment by dunderrrrrr** [comment]
Thank you! 

The comments in [omv.py](https://github.com/dunderrrrrr/openmediavault-fastapi-docker/blob/main/omv/omv.py) are from @orrpan's repository,  [orrpan/python-openmediavault](https://github.com/orrpan/python-openmediavault/blob/master/Openmediavault/Openmediavault.py). I think his version of the file fits OpenMediaVault versions prior to v6.0. I have made minor changes to it to make sure it works with version 6.0.

Currently no road map, but I'll keep investigating [OMV's rcp](https://sourceforge.net/p/openmediavault/code/515/tree/branches/0.4.x/deb/openmediavault/var/www/openmediavault/rpc/) and see if I can add more data. Pull requests are welcome ofcourse :)

**Comment by mi-hol** [comment]
closing due to lack of interest
